### ISSUE TITLE
Ansible mount check for CephFS 

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#1003]
Copy a good idea from Lassair.
https://github.com/lsst-uk/lasair-deploy/blob/87bad3e30c54f7fcd54d0469cceef366812fce4e/test.yaml#L212-L230
```
# CehpFS tests
- hosts: svc, web, ingest, sherlock, filter, parallel_ssh
  gather_facts: false
  tasks:
    - name: check that CephFS is mounted
      assert:
        that: ansible_facts.mounts | selectattr('mount', '==', '/mnt/cephfs')
        quiet: true
  tags: cephfs

# Sherlock shared FS
- hosts: sherlock
  gather_facts: false
  tasks:
    - name: check that Sherlock shared filesystem is mounted
      assert:
        that: ansible_facts.mounts | selectattr('mount', '==', '/mnt/sherlock')
        quiet: true
  tags: cephfs
```
