### ISSUE TITLE
Validation tests for the catalogs

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#82]
Need to create a set of Python scripts (command line and notebook) to validate the contents of a Gaia release.

We have some of these already, so initially just bringing them together into one set of scripts that we can run on a data set to check it has the right data.
- Tests should return PASS/FAIL, with useful messages for known errors and debug for unknown errors.
- Tests should collect timings and statistics useful for comparing the performance of different storage platforms.

**Comment by Zarquan** [comment]
At the moment we just check the row count. We could add some tests that check the data content.
* `sum`, `max` and `min` of the object id column

**Comment by Zarquan** [comment]
Expanded this to include all of the science catalogs, not just Gaia.

**Comment by Zarquan** [comment]
Assuming the current catalogs are correct, we have some initial test data for this.
```
catalogs:

  - name: "GDR2"
    sharename: "aglais-gaia-dr2"
    sharesize: "512"
    mountpath: "/data/gaia/dr2"
    rowcount: 1692919135
    partitions: 5985

  - name: "GEDR3"
    source: "/user/nch/PARQUET/TESTS/GEDR3"
    sharename: "aglais-gaia-edr3"
    sharesize: "540"
    mountpath: "/data/gaia/edr3"
    rowcount: 1811709771
    partitions: 5720

  - name: "ALLWISE"
    source: "/user/nch/PARQUET/TESTS/ALLWISE"
    sharename: "aglais-wise-allwise"
    sharesize: "350"
    mountpath: "/data/wise/allwise"
    rowcount: 747634026
    partitions: 3059

  - name: "PS1"
    source: "/user/nch/PARQUET/TESTS/PS1"
    sharename: "aglais-panstarrs-dr1"
    sharesize: "300"
    mountpath: "/data/panstarrs/dr1"
    rowcount: 1919106885
    partitions: 2553

  - name: "2MASS"
    source: "/user/nch/PARQUET/TESTS/2MASS"
    sharename: "aglais-twomass-allsky"
    sharesize: "40"
    mountpath: "/data/twomass/allsky"
    rowcount: 470992970
    partitions: 385
```
