### ISSUE TITLE
Simplify deployment status

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#885]
Current deployment status has `status` and `spec` sections .. because history. We should probably simplify the structure before too many other things begin to depend on it.
```
aglais:
  status:
    deployment:
      type: hadoop-yarn
      conf: zeppelin-26.43-spark-3.26.43
      name: iris-gaia-red-20220720
      date: 20220720T182912
      hostname: zeppelin.gaia-dmp.uk
  spec:
    openstack:
      cloud:
        base: arcus
        name: iris-gaia-red
```
