### ISSUE TITLE
Add a 'local' keyword to make make user data local 

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#891]
We are limited to creating 10 Ceph shares per [red|green|blue] project at the moment.
We can get the quota increased, but it would also be useful to be able to skip creating Ceph shares for simple test accounts by setting the account type to local.
```
users:
  - name: Iflee
    type: local
    ...
```

**Comment by Zarquan** [comment]
Better to put the type on the share.
```
  - name: "Reyesfan"
    usershare:
      type:  local
      path:  /tmp/user/Reyesfan

  - name: "Reyesfan"
    usershare:
      type:  manila
      path:  /user/Reyesfan
      manila:
        name:  aglais-user-Reyesfan
        cloud: iris-gaia-data
```

This leaves it open to have different types of share in the future.
```
  - name: "Reyesfan"
    usershare:
      type:  nfs
      path:  /user/Reyesfan
      nfs:
        host: nfs-server
        path: /nfs/users
```
